# Generated by Django 3.0.8 on 2020-07-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200703_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='best_bid',
            field=models.BooleanField(default=False),
        ),
    ]
