# Generated by Django 3.0.8 on 2020-07-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listing_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='best_bid',
        ),
    ]
